version: '3'
services:
  php:
    build:
      context: ./docker/php
    

  nginx:
    image: chelezo/myngn:latest
    ports:
      - 9191:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './src:/var/www/html'
      - './docker/volms/mysql:/var/lib/mysql'
environment:
      - MYSQL_ROOT_PASSWORD=root
      
