version: '3'
services:
  nginx:
    image: chelezo/myngn
    build:
      context: ./
    volumes:
      - './www:/var/www/html'
    ports:
      - 9191:80
    volumes:
      - './www:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: chelezo/myngn
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './mysql:/var/lib/mysql'
