version: '3.1'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'
 myngn:
   image: chelezo/myngn
   ports:
     - 9191:80
   volumes:
     - './docker/nginx/conf.d:/etc/nginx/conf.d'
   environment:
     - MYSQL_ROOT_PASSWORD=root
   volumes:
     - './docker/volms/mysql:/var/lib/mysql'

