version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'

  nginx:
    image: chelezo/myngn
    ports:
      - 9191:80
    volumes:
      - './src:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: chelezo/myngn
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './volms/mysql:/var/lib/mysql'
